on:
  schedule:
    # Runs every 5 minutes. (15 mins is recommended for stability)
    - cron: '*/600 * * * *'
  workflow_dispatch:
    # Allows you to run this workflow manually from the Actions tab

jobs:
  run-bot:
    runs-on: ubuntu-latest

    # --- ADD THIS PERMISSIONS BLOCK ---
    permissions:
      contents: write
    # ------------------------------------

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests feedparser

      - name: Run the bot script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        run: python Main.py

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update posted links history"
          file_pattern: "posted_links.txt"
